# Required metadata 
sonar.projectKey=adl-etl-telco-disaggregated-bss-crm-crm-main-frontend
sonar.projectName=adl-etl-telco-disaggregated-bss-crm-crm-main-frontend
sonar.projectVersion=1.6.2

# Project language
sonar.language=js

# Source and test configuration
sonar.sources=./

# Exclusions
sonar.exclusions=**/node_modules/**,**/*.module.ts,**/*.conf.js,**/test.ts,**/*.java,src/components/no-dashboard/NoDashboard.scss

# Coverage disabled intentionally
sonar.coverage.enabled=false
#sonar.coverage.exclusions=**/*.module.ts,**/*.conf.js,**/test.ts
# sonar.typescript.lcov.reportPaths=crm-crm-main-frontend/coverage/lcov.info

# Source encoding
sonar.sourceEncoding=UTF-8

# TypeScript configuration
sonar.typescript.tsconfigPath=tsconfig.sonar.json
