import DropdownValue from "../pages/enterprise/enterprise-crm/common-models/DropdownValue";

const currency: DropdownValue[] = [
    // { value: 'LKR', label: 'Sri Lankan Rupee' },
    { value: 'USD', label: 'US Dollar' },
    // { value: 'EUR', label: 'Euro' },
    // { value: 'GBP', label: 'British Pound' },
    // { value: 'JPY', label: 'Japanese Yen' },
    // { value: 'AUD', label: 'Australian Dollar' },
    // { value: 'CAD', label: 'Canadian Dollar' },
    // { value: 'CHF', label: 'Swiss Franc' },
    // { value: 'CNY', label: 'Chinese Yuan' },
    // { value: 'SEK', label: 'Swedish Krona' },
    // { value: 'NZD', label: 'New Zealand Dollar' },
    // { value: 'MXN', label: 'Mexican Peso' },
    // { value: 'SGD', label: 'Singapore Dollar' },
    // { value: 'HKD', label: 'Hong Kong Dollar' },
    // { value: 'NOK', label: 'Norwegian Krone' },
    // { value: 'KRW', label: 'South Korean Won' },
    // { value: 'TRY', label: 'Turkish Lira' },
    // { value: 'RUB', label: 'Russian Ruble' },
    // { value: 'INR', label: 'Indian Rupee' },
    // { value: 'BRL', label: 'Brazilian Real' },
    // { value: 'ZAR', label: 'South African Rand' },
    // { value: 'DKK', label: 'Danish Krone' },
    // { value: 'PLN', label: 'Polish Zloty' },
    // { value: 'TWD', label: 'New Taiwan Dollar' },
    // { value: 'THB', label: 'Thai Baht' },
    // { value: 'MYR', label: 'Malaysian Ringgit' },
    // { value: 'IDR', label: 'Indonesian Rupiah' },
    // { value: 'CZK', label: 'Czech Koruna' },
    // { value: 'HUF', label: 'Hungarian Forint' },
    // { value: 'ILS', label: 'Israeli Shekel' },
    // { value: 'CLP', label: 'Chilean Peso' },
    // { value: 'PHP', label: 'Philippine Peso' },
    // { value: 'AED', label: 'United Arab Emirates Dirham' },
    // { value: 'COP', label: 'Colombian Peso' },
    // { value: 'SAR', label: 'Saudi Riyal' },
    // { value: 'RON', label: 'Romanian Leu' },
    // { value: 'PEN', label: 'Peruvian Sol' },
    // { value: 'VND', label: 'Vietnamese Dong' },
    // { value: 'BDT', label: 'Bangladeshi Taka' },
    // { value: 'PKR', label: 'Pakistani Rupee' },
    // { value: 'EGP', label: 'Egyptian Pound' },
    // { value: 'NGN', label: 'Nigerian Naira' },
    // { value: 'KZT', label: 'Kazakhstani Tenge' },
    // { value: 'QAR', label: 'Qatari Riyal' },
    // { value: 'KWD', label: 'Kuwaiti Dinar' },
    // { value: 'BHD', label: 'Bahraini Dinar' },
    // { value: 'OMR', label: 'Omani Rial' },
    // { value: 'JOD', label: 'Jordanian Dinar' },
    // { value: 'LBP', label: 'Lebanese Pound' },
    // { value: 'IQD', label: 'Iraqi Dinar' },
    // { value: 'MAD', label: 'Moroccan Dirham' },
    // { value: 'DZD', label: 'Algerian Dinar' },
    // { value: 'TND', label: 'Tunisian Dinar' },
    // { value: 'LYD', label: 'Libyan Dinar' },
    // { value: 'SDG', label: 'Sudanese Pound' },
    // { value: 'KES', label: 'Kenyan Shilling' },
    // { value: 'TZS', label: 'Tanzanian Shilling' },
    // { value: 'UGX', label: 'Ugandan Shilling' },
    // { value: 'GHS', label: 'Ghanaian Cedi' },
    // { value: 'XOF', label: 'West African CFA Franc' },
    // { value: 'XAF', label: 'Central African CFA Franc' },
    // { value: 'MUR', label: 'Mauritian Rupee' },
    // { value: 'SCR', label: 'Seychellois Rupee' },
    // { value: 'MGA', label: 'Malagasy Ariary' },
    // { value: 'ZMW', label: 'Zambian Kwacha' },
    // { value: 'BWP', label: 'Botswana Pula' },
    // { value: 'NAD', label: 'Namibian Dollar' },
    // { value: 'BND', label: 'Brunei Dollar' },
    // { value: 'MMK', label: 'Myanmar Kyat' },
    // { value: 'KHR', label: 'Cambodian Riel' },
    // { value: 'LAK', label: 'Lao Kip' },
    // { value: 'MOP', label: 'Macanese Pataca' },
    // { value: 'PGK', label: 'Papua New Guinean Kina' },
    // { value: 'SBD', label: 'Solomon Islands Dollar' },
    // { value: 'TOP', label: 'Tongan Paʻanga' },
    // { value: 'FJD', label: 'Fijian Dollar' },
    // { value: 'WST', label: 'Samoan Tala' },
    // { value: 'VUV', label: 'Vanuatu Vatu' },
    // { value: 'KPW', label: 'North Korean Won' },
    // { value: 'MNT', label: 'Mongolian Tugrik' },
    // { value: 'BTN', label: 'Bhutanese Ngultrum' },
    // { value: 'NPR', label: 'Nepalese Rupee' },
    // { value: 'MVR', label: 'Maldivian Rufiyaa' },
    // { value: 'AFN', label: 'Afghan Afghani' },
    // { value: 'IRR', label: 'Iranian Rial' },
    // { value: 'YER', label: 'Yemeni Rial' },
    // { value: 'SYP', label: 'Syrian Pound' },
    // { value: 'AMD', label: 'Armenian Dram' },
    // { value: 'AZN', label: 'Azerbaijani Manat' },
    // { value: 'GEL', label: 'Georgian Lari' },
    // { value: 'KGS', label: 'Kyrgyzstani Som' },
    // { value: 'TJS', label: 'Tajikistani Somoni' },
    // { value: 'UZS', label: 'Uzbekistani Som' },
    // { value: 'BYN', label: 'Belarusian Ruble' },
    // { value: 'MDL', label: 'Moldovan Leu' },
    // { value: 'UAH', label: 'Ukrainian Hryvnia' },
    // { value: 'ALL', label: 'Albanian Lek' },
    // { value: 'BAM', label: 'Bosnia and Herzegovina Convertible Mark' },
    // { value: 'HRK', label: 'Croatian Kuna' },
    // { value: 'MKD', label: 'Macedonian Denar' },
    // { value: 'RSD', label: 'Serbian Dinar' },
    // { value: 'ISK', label: 'Icelandic Krona' },
    // { value: 'BGN', label: 'Bulgarian Lev' },
    // { value: 'HNL', label: 'Honduran Lempira' },
    // { value: 'GTQ', label: 'Guatemalan Quetzal' },
    // { value: 'CRC', label: 'Costa Rican Colón' },
    // { value: 'PAB', label: 'Panamanian Balboa' },
    // { value: 'DOP', label: 'Dominican Peso' },
    // { value: 'HTG', label: 'Haitian Gourde' },
    // { value: 'JMD', label: 'Jamaican Dollar' },
    // { value: 'TTD', label: 'Trinidad and Tobago Dollar' },
    // { value: 'BBD', label: 'Barbadian Dollar' },
    // { value: 'BZD', label: 'Belize Dollar' },
    // { value: 'BMD', label: 'Bermudian Dollar' },
    // { value: 'KYD', label: 'Cayman Islands Dollar' },
    // { value: 'ANG', label: 'Netherlands Antillean Guilder' },
    // { value: 'AWG', label: 'Aruban Florin' },
    // { value: 'BSD', label: 'Bahamian Dollar' },
    // { value: 'CUC', label: 'Cuban Convertible Peso' },
    // { value: 'CUP', label: 'Cuban Peso' },
    // { value: 'DZD', label: 'Algerian Dinar' },
    // { value: 'DJF', label: 'Djiboutian Franc' },
    // { value: 'ERN', label: 'Eritrean Nakfa' },
    // { value: 'ETB', label: 'Ethiopian Birr' },
    // { value: 'GMD', label: 'Gambian Dalasi' },
    // { value: 'GNF', label: 'Guinean Franc' },
    // { value: 'LSL', label: 'Lesotho Loti' },
    // { value: 'LRD', label: 'Liberian Dollar' },
    // { value: 'MWK', label: 'Malawian Kwacha' },
    // { value: 'MZN', label: 'Mozambican Metical' },
    // { value: 'RWF', label: 'Rwandan Franc' },
    // { value: 'SZL', label: 'Swazi Lilangeni' },
    // { value: 'SOS', label: 'Somali Shilling' },
    // { value: 'SSP', label: 'South Sudanese Pound' },
    // { value: 'STD', label: 'São Tomé and Príncipe Dobra' },
    // { value: 'TMT', label: 'Turkmenistani Manat' },
    // { value: 'UGX', label: 'Ugandan Shilling' },
    // { value: 'ZWL', label: 'Zimbabwean Dollar' },
];

export default currency;