export const BASE_PATH = import.meta.env.VITE_BASE_PATH;

console.log("Environment Variables: ",import.meta.env);

const INTERNAL_ROUTES = {
    LOGIN_PAGE: BASE_PATH + "/login",
    AUTH_CODE_RE_DIRECTION_PAGE: BASE_PATH + "/auth-code",
    GET_TEMP_TOKEN_PAGE_SUCCESS: BASE_PATH + "/internal/success/:tempToken",
    GET_TEMP_TOKEN_PAGE_ERROR: BASE_PATH + "/internal/error/:errorType",
    HOME_PAGE: BASE_PATH + "/home",
    SESSION_EXPIRE_PAGE: BASE_PATH + "/session-expire",
    UNAUTHORIZED_ACCESS_PAGE: BASE_PATH + "/unauthorized-access",
    CUSTOMER_PROFILE: BASE_PATH + "/customer-profile",
    CUSTOMER: BASE_PATH + "/customer",
    ACTION_LOGS: BASE_PATH + "/action-logs",
    USERS: BASE_PATH + "/user-management",
    ROLES: BASE_PATH + "/roles",
    PERMISSIONS: BASE_PATH + "/permissions",
    ACCOUNTS: BASE_PATH + "/accounts",
    SINGLE_ACCOUNT_PAGE: BASE_PATH + "/accounts/:id",
    SINGLE_CONTACT_PAGE: BASE_PATH + "/contacts/:id",
    SINGLE_LEAD_PAGE: BASE_PATH + "/leads/:id",
    COMPONENTS: BASE_PATH + "/:component/:id",
    CONTACTS: BASE_PATH + "/contacts",
    LEADS: BASE_PATH + "/leads",
    OPPORTUNITIES: BASE_PATH + "/opportunities",
    PRODUCTS: BASE_PATH + "/product",
    CREATE_PRODUCT: BASE_PATH + "/product/create-product",
    PRODUCT_CONFIGURATION: BASE_PATH + "/product/product-configuration",
    PRODUCT_FEDERATION_PROCESS: BASE_PATH + "/product/federation-process",
    PRODUCT_FEDERATION_WORKFLOW: BASE_PATH + "/product/federation-workflow",
    PRODUCT_SERVICE_CATALOG: BASE_PATH + "/product/product-service-catalog",
    PRODUCT_RESOURCE_CATALOG: BASE_PATH + "/product/resource-catalog",
    CPQ_IFRAME: BASE_PATH + "/cpq",
    CPQ_HOME: BASE_PATH + "/cpq-home",
    EXTENSIONS: BASE_PATH + "/extension",
    CONFIGURATIONS: BASE_PATH + "/settings",
    SETTINGS_ACTION_LOGS: BASE_PATH + "/setting/action-logs",
    SETTINGS_EXTENSIONS: BASE_PATH + "/settings/extensions",
    SETTINGS: BASE_PATH + "/settings",
    DYNAMIC_EXTENSION: BASE_PATH + "/external-service",
    WORKFLOW: BASE_PATH + "/workflow",
    APPROVAL_WORKFLOW: BASE_PATH + "/workflow/approval-workflow",
    CREATE_APPROVAL_REQUEST: BASE_PATH + "/workflow/create-approval-request",
    APPROVAL_REQUEST_MANAGEMENT: BASE_PATH + "/workflow/approval-request-management",
    ALL_APPROVAL_REQUEST_MANAGEMENT: BASE_PATH + "/workflow/all-approval-request-management",
    CASE_TYPE: BASE_PATH + "/case-management/case-type",
    CASE_REQUEST_MANAGEMENT: BASE_PATH + "/case-management/case-request-management",
    TROUBLE_TICKET: BASE_PATH + "/case-management/trouble-ticket",
}

export default INTERNAL_ROUTES;