# Use official node image as the base image
FROM 10.200.140.150:5000/node-build-react:LANGUAGE_VERSION AS build

# Stage 0: Compile and Build angular codebase

# Set the working directory
RUN mkdir /app

WORKDIR /app

# copy package.json to app directory
#COPY . /app
COPY package.json /app
COPY /envfiles/.env.development /app
COPY /envfiles/.env.demo /app

RUN ls -ltr /app/*

# Install all the dependencies
RUN npm install

#copy code to app directory
COPY . /app
RUN ls -ltr /app/*

# Install all the dependencies

# development environment build commond
RUN npm run build

# Demo environment build commond
#RUN npm run build:demo

# Telstra environment build commond
# RUN npm run build:telstra

RUN ls -la /app/*

RUN ls -la /app/dist
# Stage 2: Serve app with nginx server

# Use official nginx image as the base image
FROM nginx:latest
#RUN rm -f /etc/nginx/conf.d/default.conf
#COPY mascom.conf /etc/nginx/conf.d/
RUN sed -i '10i try_files $uri /index.html;' /etc/nginx/conf.d/default.conf

# Copy the build output to replace the default nginx contents.
COPY --from=build /app/dist /usr/share/nginx/html

RUN cd /usr/share/nginx && ls

RUN chmod -R 775 /usr/share/nginx/html/*
